version: "3.7"
services:
    bpgen:
        build:
            context: .
        ports:
            - "5001:5001"
            - "5000:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        volumes:
            - sqldata:/var/lib/db
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "<YourStrong!Passw0rd>"
            ACCEPT_EULA: "Y"

volumes:
  sqldata:
    name: sqldata
